name: Build Module

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download and extract ECH Workers binary
      run: |
        chmod +x build.sh
        ./build.sh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: echwk-module
        path: echwk-module.zip  # Ensure this is the correct path
